# Generated by Django 5.0.3 on 2024-04-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_variation_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='variation_price',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
