# Generated by Django 5.0.3 on 2024-04-05 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_variation_variation_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='variation_price',
        ),
    ]
