# Generated by Django 5.0.3 on 2024-04-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_variation_variation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='variation_price',
            field=models.IntegerField(null=True),
        ),
    ]
