# Generated by Django 5.0.3 on 2024-04-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_variation_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
