# Generated by Django 5.0.3 on 2024-04-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_productgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image_big1',
            field=models.ImageField(default=1, upload_to='images/products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_big2',
            field=models.ImageField(default=1, upload_to='images/products'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='ProductGallery',
        ),
    ]
