# Generated by Django 5.0.3 on 2024-04-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_product_product_image_big1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='MRP_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
