# Generated by Django 5.0.3 on 2024-04-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_product_mrp_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='variation_MRP_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
