# Generated by Django 5.0.3 on 2024-04-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_variation_variation_mrp_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_product',
            field=models.BooleanField(default=False),
        ),
    ]
