# Generated by Django 5.0.3 on 2024-04-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_product_best_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model3d',
            field=models.FileField(blank=True, null=True, upload_to='3d_objects'),
        ),
    ]
