# Generated by Django 5.0.3 on 2024-04-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_product_model3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_brand',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
