# Generated by Django 5.0.4 on 2024-05-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_description',
        ),
        migrations.AddField(
            model_name='category',
            name='home_page_show',
            field=models.BooleanField(default=False),
        ),
    ]
